export const STRIPE_PAY_REQUEST = 'STRIPE_PAY_REQUEST'
export const STRIPE_PAY_SUCCESS = 'STRIPE_PAY_SUCCESS'
export const STRIPE_PAY_FAIL = 'STRIPE_PAY_FAIL'
export const STRIPE_PAY_RESET = 'STRIPE_PAY_RESET'
